version: "3"

tasks:
  default:
    desc: "Display this help message"
    cmds:
      - task -l

  # General
  all:
    desc: "Run all tasks"
    cmds:
      - task lint
      - task test
      - task fmt
      - task docker-lint
      - task api-lint

  # Go
  go:lint:
    desc: "Lint Go code"
    cmds:
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go vet ./...
      - staticcheck ./...

  go:test:
    desc: "Run Go tests"
    cmds:
      - go build ./...
      - go test -v ./...

  go:fmt:
    desc: "Format Go code"
    cmds:
      - go fmt ./...
      - go install golang.org/x/tools/cmd/goimports@latest
      - find . -print | grep --regex '.*\.go' | xargs goimports -w -local "github.com/yashikota/chronotes"

  # Docker
  docker:dev:
    desc: "Run development environment"
    cmds:
      - docker compose up --build

  docker:build:
    desc: "Build Docker image"
    cmds:
      - docker build -t chronotes .

  docker:lint:
    desc: "Lint Dockerfile"
    cmds:
      - docker run --rm -i hadolint/hadolint < Dockerfile

  # API
  # api:ogen:
  #   desc: "Generate OpenAPI specification"
  #   cmds:
  #     - docker run --rm -v {{.PWD}}:/wd ghcr.io/ogen-go/ogen:v1.4.1 --target wd/pkg/ogen --clean wd/docs/api/bundled.yaml

  api:lint:
    desc: "Lint API documentation"
    cmds:
      - task: tsp
      - docker run --rm -v {{.PWD}}:/spec redocly/cli:1.25.2 lint --config docs/api/redoc.yaml docs/api/bundled.yaml

  api:tsp:
    desc: "Generate Open API from TypeSpec"
    cmds:
      - docker run --rm -v {{.PWD}}:/wd --workdir="/wd" -t azsdkengsys.azurecr.io/typespec compile docs/spec
      - task: split

  api:split:
    desc: "Split OpenAPI specification"
    cmds:
      - rm -rf docs/spec/components docs/spec/paths
      - docker run --rm -v {{.PWD}}:/spec redocly/cli:1.25.2 split docs/api/bundled.yaml --outDir=docs/api

  # api:bundle:
  #   desc: "Bundle OpenAPI specification"
  #   cmds:
  #     - docker run --rm -v {{.PWD}}:/spec redocly/cli:1.25.2 bundle docs/api/openapi.yaml -o docs/api/bundled.yaml
