version: "3"

tasks:
  default:
    desc: "Display this help message"
    cmds:
      - task -l

  # Go
  lint:
    desc: "Run Go linters"
    cmds:
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go vet ./...
      - staticcheck ./...

  test:
    desc: "Run Go tests"
    cmds:
      - go build ./...
      - go test -v ./...

  fmt:
    desc: "Format Go code"
    cmds:
      - go fmt ./...

  # Docker
  dev:
    desc: "Run development environment"
    cmds:
      - docker compose up --build

  build:
    desc: "Build Docker image"
    cmds:
      - docker build -t chronotes .

  docker-lint:
    desc: "Lint Dockerfile"
    cmds:
      - docker run --rm -i hadolint/hadolint < Dockerfile

  # API
  api-lint:
    desc: "Lint API documentation"
    cmds:
      - task: tsp
      - docker run --rm -v {{.PWD}}:/spec redocly/cli:1.25.2 lint --config docs/api/redoc.yaml docs/api/openapi.yaml

  tsp:
    desc: "Generate Open API from TypeSpec"
    cmds:
      - docker run --rm -v {{.PWD}}:/wd --workdir="/wd" -t azsdkengsys.azurecr.io/typespec compile docs/spec
      - task: split

  split:
    desc: "Split OpenAPI specification"
    cmds:
      - docker run --rm -v {{.PWD}}:/spec redocly/cli:1.25.2 split docs/api/openapi.yaml --outDir=docs/api

  bundle:
    desc: "Bundle OpenAPI specification"
    cmds:
      - task: tsp
      - docker run --rm -v {{.PWD}}:/spec redocly/cli:1.25.2 bundle docs/api/openapi.yaml -o docs/api/bundled.yaml

  docs:
    desc: "Generate API documentation"
    cmds:
      - task: bundle
      - docker run --rm -v {{.PWD}}:/spec redocly/cli:1.25.2 build-docs docs/api/bundled.yaml --o docs/api/redoc.html
