name: API Docs

on:
  pull_request:
  workflow_dispatch:

jobs:
  job:
    name: API Docs
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Build API Docs
        run: make docs

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update API Docs"
