name: API docs

on:
  pull_request:
  workflow_dispatch:

jobs:
  job:
    name: API docs
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API docs
        run: task docs

      - name: Check for changes
        run: git diff --exit-code
