name: API bundle

on:
  pull_request:
  workflow_dispatch:

jobs:
  job:
    name: API bundle
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: API bundle
        run: task bundle

      - name: Check for changes
        continue-on-error: true
        run: git diff --name-only --exit-code

      - name: Error check
        if: ${{ steps.error_execution.outcome == "failure" }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Please run `task bundle`" > /tmp/comment
          gh pr comment "${PR_NUMBER}" -F /tmp/comment
