name: Go fmt

on:
  pull_request:
  workflow_dispatch:

jobs:
  job:
    name: Go fmt
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: fmt
        run: task go:fmt

      - name: Check for changes
        continue-on-error: true
        run: git diff --name-only --exit-code

      - name: Error check
        if: ${{ steps.error_execution.outcome == 'failure' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Please run `task go:fmt`" > /tmp/comment
          gh pr comment "${PR_NUMBER}" -F /tmp/comment
