name: Go fmt

on:
  pull_request:
  workflow_dispatch:

jobs:
  job:
    name: Go fmt
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Go Fmt
        run: go fmt ./...

      - name: Check for changes
        run: git diff --name-only --exit-code
