name: Go Fmt

on:
  pull_request:
  workflow_dispatch:

jobs:
  job:
    name: Go Fmt
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Go Fmt
        run: go fmt ./...

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Check if there are changes after go fmt
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "Go fmt"
            git push origin ${{ github.head_ref }}
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
