name: Go Lint

on:
  push:
  workflow_dispatch:

jobs:
  job:
    name: Go Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
