name: Go Test

on:
  push:
  workflow_dispatch:
env :
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

jobs:
  job:
    name: Go Test
    runs-on: ubuntu-latest
    timeout-minutes: 5


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build and Test
        run: make test
