name: Test coverage

on:
  push

env :
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  DISCORDTOKEN: ${{ secrets.DISCORD_TOKEN }}
  
jobs:
  job:
    name: Test coverage
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -coverprofile=coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
